[2021-05-17 07:30:36,445] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: etl_postgresql2mongo.read_from_MongoDB 2021-05-17T07:25:00+00:00 [queued]>
[2021-05-17 07:30:36,462] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: etl_postgresql2mongo.read_from_MongoDB 2021-05-17T07:25:00+00:00 [queued]>
[2021-05-17 07:30:36,462] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2021-05-17 07:30:36,462] {taskinstance.py:1043} INFO - Starting attempt 1 of 1
[2021-05-17 07:30:36,462] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2021-05-17 07:30:36,471] {taskinstance.py:1063} INFO - Executing <Task(PythonOperator): read_from_MongoDB> on 2021-05-17T07:25:00+00:00
[2021-05-17 07:30:36,475] {standard_task_runner.py:52} INFO - Started process 140 to run task
[2021-05-17 07:30:36,478] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'etl_postgresql2mongo', 'read_from_MongoDB', '2021-05-17T07:25:00+00:00', '--job-id', '29', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/csv_postgres_2_mongo.py', '--cfg-path', '/tmp/tmpybqqf4_3', '--error-file', '/tmp/tmp9wqayzls']
[2021-05-17 07:30:36,479] {standard_task_runner.py:77} INFO - Job 29: Subtask read_from_MongoDB
[2021-05-17 07:30:36,518] {logging_mixin.py:104} INFO - Running <TaskInstance: etl_postgresql2mongo.read_from_MongoDB 2021-05-17T07:25:00+00:00 [running]> on host d0d96188f4f7
[2021-05-17 07:30:36,558] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=etl_postgresql2mongo
AIRFLOW_CTX_TASK_ID=read_from_MongoDB
AIRFLOW_CTX_EXECUTION_DATE=2021-05-17T07:25:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-05-17T07:25:00+00:00
[2021-05-17 07:30:36,562] {logging_mixin.py:104} WARNING - /home/airflow/.local/lib/python3.6/site-packages/pymongo/topology.py:162 UserWarning: MongoClient opened before fork. Create MongoClient only after forking. See PyMongo's documentation for details: https://pymongo.readthedocs.io/en/stable/faq.html#is-pymongo-fork-safe
[2021-05-17 07:30:36,582] {logging_mixin.py:104} INFO - number of documents in mongoDB =  300
[2021-05-17 07:30:36,582] {python.py:118} INFO - Done. Returned value was: None
[2021-05-17 07:30:36,593] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=etl_postgresql2mongo, task_id=read_from_MongoDB, execution_date=20210517T072500, start_date=20210517T073036, end_date=20210517T073036
[2021-05-17 07:30:36,621] {taskinstance.py:1220} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-05-17 07:30:36,649] {local_task_job.py:146} INFO - Task exited with return code 0
