[2021-05-17 07:25:29,504] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: etl_postgresql2mongo.push_DF_to_Mongo 2021-05-17T07:20:00+00:00 [queued]>
[2021-05-17 07:25:29,529] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: etl_postgresql2mongo.push_DF_to_Mongo 2021-05-17T07:20:00+00:00 [queued]>
[2021-05-17 07:25:29,530] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2021-05-17 07:25:29,530] {taskinstance.py:1043} INFO - Starting attempt 1 of 1
[2021-05-17 07:25:29,530] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2021-05-17 07:25:29,545] {taskinstance.py:1063} INFO - Executing <Task(PythonOperator): push_DF_to_Mongo> on 2021-05-17T07:20:00+00:00
[2021-05-17 07:25:29,552] {standard_task_runner.py:52} INFO - Started process 76 to run task
[2021-05-17 07:25:29,557] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'etl_postgresql2mongo', 'push_DF_to_Mongo', '2021-05-17T07:20:00+00:00', '--job-id', '24', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/csv_postgres_2_mongo.py', '--cfg-path', '/tmp/tmps9bfkw58', '--error-file', '/tmp/tmpy4501g2q']
[2021-05-17 07:25:29,557] {standard_task_runner.py:77} INFO - Job 24: Subtask push_DF_to_Mongo
[2021-05-17 07:25:29,621] {logging_mixin.py:104} INFO - Running <TaskInstance: etl_postgresql2mongo.push_DF_to_Mongo 2021-05-17T07:20:00+00:00 [running]> on host d0d96188f4f7
[2021-05-17 07:25:29,681] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=etl_postgresql2mongo
AIRFLOW_CTX_TASK_ID=push_DF_to_Mongo
AIRFLOW_CTX_EXECUTION_DATE=2021-05-17T07:20:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-05-17T07:20:00+00:00
[2021-05-17 07:25:29,721] {logging_mixin.py:104} WARNING - /home/airflow/.local/lib/python3.6/site-packages/pymongo/topology.py:162 UserWarning: MongoClient opened before fork. Create MongoClient only after forking. See PyMongo's documentation for details: https://pymongo.readthedocs.io/en/stable/faq.html#is-pymongo-fork-safe
[2021-05-17 07:25:29,745] {python.py:118} INFO - Done. Returned value was: None
[2021-05-17 07:25:29,763] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=etl_postgresql2mongo, task_id=push_DF_to_Mongo, execution_date=20210517T072000, start_date=20210517T072529, end_date=20210517T072529
[2021-05-17 07:25:29,797] {taskinstance.py:1220} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2021-05-17 07:25:29,808] {local_task_job.py:146} INFO - Task exited with return code 0
